config/routes.rb
Rails.application.routes.draw do
  
  get 'admin/index' , as: 'adminindex'
  get 'blog/index',as: 'blog_index'
  post 'admin/contentsave', to: 'admin#contentsave', as: 'contentsave'
  get 'prevent/index', as: "prevent"
  get 'information/index', as:"info"
  get 'admin/edit/:id',to: 'admin#edit', as: 'edit'
  post 'admin/edittop3/:id', to: 'admin#edittop3' ,as: 'edittop3'
  post 'admin/edittop3update/:id', to: 'admin#edittop3update', as:'edittop3update'
  patch 'admin/update/:id', to: 'admin#contentupdate', as: 'contentupdate'
  get 'blog/contentpage/:id' , to: 'blog#contentpage', as: 'contentpage'
  get 'admin/sign_in', to: 'admin#sign_in', as: 'sign_in'
post 'admin/checksignin', to: 'admin#checksignin', as: 'checksignin'
    namespace :api do
    namespace :v1 do
post 'home/sendcitydata', to: 'home#sendcitydata' ,as: 'api'
post 'admin/deletepost', to: 'admin#deletepost', as: 'deletepost'
    end
end
get 'home/index'
root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/content.rb
class Content < ApplicationRecord
	has_rich_text :body
	has_one_attached :img
end

app/models/ind1.rb
class Ind1 < ApplicationRecord


def self.checkpre(name)
if(!Ind1.find_by(name: name))
	return 0
else
	return (Ind1.find_by(name: name).tcci)
end
end

def self.dataextract(name)
return [["Indian National Confirmed Cases",Ind1.find_by(name: name).tcci],["Cured",Ind1.find_by(name: name).cured],["Deaths",Ind1.find_by(name: name).death]]
end
end

app/models/info.rb
class Info < ApplicationRecord
 require 'nokogiri'
  require 'httparty'


  def self.initscrap
  	doc=HTTParty.get("https://www.mohfw.gov.in/")
  	@parse_page ||= Nokogiri::HTML(doc)
   
 # infom= @parse_page.css('tbody')
 # infosub=@parse_page.css('div.content.newtab').css('p')
 infom=@parse_page.css('ul')
 infosub=@parse_page.css('div.status-update')
 state_table=@parse_page.css('table.table.table-striped').children[3]
 infosub=infosub.children[1].text
 i=0


update_date=infosub.split(': ').last.split(',').first
update_time=infosub.split(', ').last.split(' GMT').first

update_date=update_date.to_date
update_time=Time.parse(update_time).strftime("%H:%M:%S")

if(Info.all.count==0)
	ctime=Time.at(0).strftime("%H:%M:%S")
	cdate=Time.at(0).to_date

else
ctime=Info.last.time_created

ctime=ctime.strftime("%H:%M:%S")
cdate=Info.last.date_created.to_date
end

puts "ARPIT"

infom=infom[6].children
# s=infom.length

# if(update_date >cdate || update_time>ctime )

#  infom.each do |row|
#   puts i
# puts i%2

#  if (i%2==0 || i> s-4)
#   i=i+1
#   next
  
#  end


# if(!Ind1.find_by(name: row.children[3].text))

# ind= Ind1.create(name: row.children[3].text, tcci: row.children[5].text.to_i ,cured: row.children[9].text.to_i, death: row.children[11].text.to_i)

# else
# Ind1.find_by(name: row.children[3].text).update(tcci: row.children[5].text.to_i ,cured: row.children[9].text.to_i, death: row.children[11].text.to_i)	
#   end
#    i=i+1
# end
#   Info.create(time_created: update_time,date_created: update_date, ttcci: Ind1.sum(:tcci), tcured: Ind1.sum(:cured), tdeath: Ind1.sum(:death))

# end

if(update_date >cdate || update_time>ctime )
activec=infom[1].children[3].text.to_i
curec=infom[3].children[3].text.to_i
deathc= infom[5].children[3].text.to_i
migrate=infom[7].children[3].text.to_i

 state_table.children.each do |row|
  puts i
puts i%2

 if (i%2==0)
  i=i+1
  next
 
 end

if(!Ind1.find_by(name: row.children[3].text))

ind= Ind1.create(name: row.children[3].text, tcci: row.children[5].text.to_i ,cured: row.children[7].text.to_i, death: row.children[9].text.to_i)

else
Ind1.find_by(name: row.children[3].text).update(tcci: row.children[5].text.to_i ,cured: row.children[7].text.to_i, death: row.children[9].text.to_i)	
  end
   i=i+1
   if(row.children[3].text == 'West Bengal')
break
end
end
Info.create(time_created: update_time,date_created: update_date, ttcci: activec+curec+deathc+migrate, tcured: curec, tdeath: deathc)
 end
 
end
end

app/models/top3.rb
class Top3 < ApplicationRecord
has_one :content 	
	def self.initdat
t3=Content.limit(3).select(:id)
t3.each do |t|
Top3.create(post_id: t.id)
	end
	end


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate , except: [:sign_in,:checksignin]
    def index
  	@newpage=Content.new
  	@tcontent= Content.all
  	@top3= Top3.all
  end
  def contentsave
  	Content.create(title: params[:content][:title],body: params[:content][:body] , date: params[:content][:date], img: params[:content][:img] ,author: params[:content][:author],metadesc: params[:content][:metadesc],metakey: params[:content][:metakey])
  redirect_to adminindex_path
  end
  def edit
@content= Content.find(params[:id])
  end
  def contentupdate
  Content.find(params[:id]).update(title: params[:content][:title],body: params[:content][:body] , date: params[:content][:date], img: params[:content][:img] ,author: params[:content][:author],metadesc: params[:content][:metadesc],metakey: params[:content][:metakey])
  redirect_to adminindex_path
  end
def edittop3
@id=Top3.find_by(post_id: params[:id])
end
def edittop3update
	Top3.find(params[:id]).update(post_id: params[:id][:post_id])
	redirect_to adminindex_path
	end
	def sign_in
	end
	def checksignin
		username= params[:username]
		password= params[:password]
		a=Admin.find_by(username: username)
		if(a.password==password)
			redirect_to adminindex_path
		session[:user_id]=a.id
		else
			redirect_to sign_in_path
		end
	end
	def authenticate
if !session[:user_id]
	redirect_to sign_in_path
end
	end

end

app/controllers/api/v1/admin_controller.rb
module Api
	module V1
		class AdminController < ApplicationController
	skip_before_action :verify_authenticity_token

def deletepost
post_id= params[:id].to_i

Content.find(post_id).delete
end
def editpost
post_id=params[:id].to_i
content=Content.find(post_id)
data=[
title: content.title,
author: content.author,
body: content.body,
img: content.img,
date: content.date,
metakey: content.metakey,
metadesc: content.metadesc

]
return render json: data
end

end
end
end

app/controllers/api/v1/home_controller.rb
module Api
	module V1
		class HomeController < ApplicationController
	skip_before_action :verify_authenticity_token
	def sendcitydata
		city_name=Ind1.find_by(name:params[:name])
		puts params[:name]
		data=[
			name:city_name.name,
			tcci: city_name.tcci,
			cured: city_name.cured,
			death: city_name.death
		]
return render json: data
	end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  include ActionText::Attachable
  def index
  @contents=Content.limit(10)
  end
  def contentpage
@id=params[:id]
@data=Content.find(@id)

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  def index
  end
end

app/controllers/prevent_controller.rb
class PreventController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/prevent_helper.rb
module PreventHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
    
    <% end %>
  </figcaption>
</figure>

app/views/admin/_editfile.html.erb
<div id="editpost">
	<div id="editpost_child">
	<div style="display: flex;justify-content: space-between;">	<h3 style="text-align: center;color: #6b7277;cursor: pointer">Edit Post</h3><div id="close" style="cursor: pointer"><i  class="fas fa-times-circle"></i></div></div><br><br>
<%=form_for content , url: contentupdate_path(content.id) do |f|%>
<%=f.text_field :title , class: 'form-control', placeholder: 'Title'%><br>
<%=f.text_field :author,class: 'form-control', placeholder: 'Author' %><br>
<%=f.date_field :date,class: 'form-control' %><br>


<%=f.label "Thumbnail"%><br>
<%=f.file_field :img%><br><br>
<%=f.rich_text_area :body %><br>
<%=f.text_field :metakey,class: 'form-control', placeholder: 'Meta Keywords' %><br>
<%=f.text_field :metadesc,class: 'form-control', placeholder: 'Meta Description' %><br>
<%=f.submit :class => 'btn btn-primary'%>
<%end%>
</div>
</div>
<script type="text/javascript">
	$('#close').click(function(){
		console.log('run');
		$('#editpost').remove();
	});
</script>

app/views/admin/_editfiletop3.html.erb
<div id="editpost">
	<div id="editpost_child">
	<div style="display: flex;justify-content: space-between;">	<h3 style="text-align: center;color: #6b7277;">Edit Post Id For Top 3</h3><div id="close2" style="cursor: pointer"><i  class="fas fa-times-circle"></i></div></div><br><br>
<%=form_for id, url: edittop3update_path(id.id) do |f|%>
<%=f.number_field :post_id , class: 'form-control', placeholder: 'post Id'%><br>

<%=f.submit :class => 'btn btn-primary'%>
<%end%>
</div>
</div>
<script type="text/javascript">
	$('#close2').click(function(){
		console.log('run');
		$('#editpost').remove();
	});
</script>

app/views/admin/edit.js.erb
var editpost = $('<%= escape_javascript render "editfile", content: @content %>');
$('body').append(editpost);

app/views/admin/edittop3.js.erb
var editpost2 = $('<%= escape_javascript render "editfiletop3", id: @id %>');
$('body').append(editpost2);

app/views/admin/index.html.erb
<div id="adminpanel">
	<div id="contentcreate">
		<h2>Create New Post</h2>
<%=form_for @newpage , url: contentsave_path do |f|%>
<%=f.text_field :title , class: 'form-control', placeholder: 'Title'%><br>
<%=f.text_field :author,class: 'form-control', placeholder: 'Author' %><br>
<%=f.date_field :date,class: 'form-control' %><br>
<%=f.label "Thumbnail"%><br>
<%=f.file_field :img%><br><br>
<%=f.rich_text_area :body %><br>
<%=f.text_field :metakey,class: 'form-control', placeholder: 'Meta Keywords' %><br>
<%=f.text_field :metadesc,class: 'form-control', placeholder: 'Meta Description' %><br>
<%=f.submit :class => 'btn btn-primary'%>

<%end%>
</div>
<div>
<div id="outputadmindiv">
	<h2>All Posts</h2>
	<%if @tcontent==nil%>
	<div>
		<p>NO DATA</p>
	</div>
	<%else%>
	<table id="admintable" class="display compact stripe hover">
	<thead>
		<th>S.no</th>
		<th>Id</th>
		<th>Title</th>
		<th>Author</th>
		<th>Date of Creation</th>
		<th>Delete</th>
		<th>Edit</th>
	</thead>
	<tbody>
<%i=1%>
	<%@tcontent.each do |t|%>
<tr>
<td><%=i%></td>
<td><%=t.id%></td>
<td><%=t.title%></td>
<td><%=t.author%></td>
<td><%=t.date.to_date%></td>
<td class="post_delete" style="cursor: pointer "><i class="fas fa-trash-alt"></i></td>
<td class="post_edit"><%= link_to "Edit", edit_path(t.id), remote: true %>
</td>
<%i=i+1%>
</tr>
<%end%>
</tbody>
</table>
	<%end%>
	</div>
<div id="admin_top3_div"> 
<h2>Top 3</h2>
	<%if Top3.all.count==0 %>
	<%Top3.initdat%>
	<%end%>
	<%f=1%>
	
<table  id="top3table" class="display compact stripe hover">
	<thead>
		<th>S.no</th>
		<th>Article ID</th>
		<th>Title</th>
		<th>Edit/Change</th>
	</thead>
	<tbody>
		<%@top3.each do |t|%>
		<tr>
			<td><%=f%></td>
			<td><%=t.post_id%></td>
			<td><%=Content.find(t.post_id).title%></td>
			<td><%= link_to "Edit", edittop3_path(t.post_id), remote: true,method: 'post' %></td>
		</tr>
		<%end%>
	</tbody>
</table>
	
	
</div>
</div>
</div>

<script type="text/javascript">
	$(document).ready( function () {
 var admintable =   $('#admintable').DataTable();
  var top3table =   $('#top3table').DataTable();
    $('.post_delete').click(function(){
    	console.log($(this)[0].parentElement.children[1].textContent);
    $.ajax({
    	url: '/api/v1/admin/deletepost',
    	type: 'post',
    	data: {id: $(this)[0].parentElement.children[1].textContent},
    	success: function(){
    		console.log('done');
    	admintable.row($(this)[0].parentElement).remove().draw();
    	}
    });
});

    $('.top3_delete').click(function(){

    });
} );
	

</script>

app/views/admin/sign_in.html.erb
<div style="height:100vh">
<h3>LOGIN</h3>
<%= form_tag checksignin_path , method: 'post' do%>
<%=text_field_tag :username ,"", class: 'form-control', placeholder: 'Username'%><br>
<%=password_field_tag :password ,"", class: 'form-control', placeholder: 'Password'%><br>
<%=submit_tag "Sign in"%>
<%end%>
</div>

app/views/blog/contentpage.html.erb
<meta name="keyword" content="<%=@data.metakey%>">
<meta name="description" content="<%=@data.metadesc%>">
<div class="contentblog_parent" style="min-height: 100vh;">
<div class="contentblog">
<h1 class="ctitle"><%=@data.title%></h1><br>
<div class="cauthor"><p><%=@data.author%></p><br>
<p  class="ccalender"><i class="fas fa-calendar-week"></i> <%=@data.date.to_date.strftime("%d/%m/%y")%></p><br></div>
<p class="cbody"><%=@data.body%></p><br>
</div>
</div>

app/views/blog/index.html.erb
<div id="blogindex">
<div id="main_blog_front">
	<a href="<%=contentpage_path(Top3.first.post_id)%>">
		<div id="mbf1" style="background-image: url(<%=rails_blob_url(Content.find(Top3.first.post_id).img)%>)">
		<div class="first_text"><h2 style="text-align: center;"><%=Content.find(Top3.first.post_id).title%></h2>
		</div>
	</div>
</a>
	<div id="main_blog_sec">
	<a href="<%=contentpage_path(Top3.second.post_id)%>"><div class="mbf2" style="background-image: url(<%=rails_blob_url(Content.find(Top3.second.post_id).img)%>)">
			<div style="height:70%"></div>
				<div class="first_text"><h2 style="text-align: center;"><%=Content.find(Top3.second.post_id).title%></h2>
		</div>

			
		</div>
	</a>
	<a href="<%=contentpage_path(Top3.third.post_id)%>">	<div class="mbf2" style="background-image: url(<%=rails_blob_url(Content.find(Top3.last.post_id).img)%>">
			<div style="height:70%;"></div>
				<div class="first_text"><h2 style="text-align: center;"><%=Content.find(Top3.last.post_id).title%></h2>
		</div>
			
		</div>
	</a>
	</div>
</div>
<h2 id="latestnews" >Latest News</h2>
<div id="secondary_blog_front">

	<%@contents.each do |t|%>
	<a href="<%=contentpage_path(t.id)%>">
<div class="blog_points">
	
	<div id="bpimg"><%=image_tag t.img%></div>
	<div class="sectitle"><p><%=t.title%></p></div>
</div>
</a>
	<%end%>
</div>
</div>

app/views/information/index.html.erb
<div style="min-height: 95vh">
<div id="info_about">
	<p>
Coronavirus disease 2019 (COVID-19) is an infectious disease caused by severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2). The disease was first identified in 2019 in Wuhan, Central China, and has since spread globally, resulting in the 2019–20 coronavirus pandemic. Common symptoms include fever, cough, and shortness of breath. Muscle pain, sputum production and sore throat are less common. While the majority of cases result in mild symptoms, some progress to severe pneumonia and multi-organ failure. As of 20 March 2020, the rate of deaths per number of diagnosed cases is 4.1%; however, it ranges from 0.2% to 15% depending on age and other health problems.
</p>
</div>
<div id="videos">
	<h2>Watch These To Learn More</h2>
<div>
	<iframe width="560" height="315" src="https://www.youtube.com/embed/BtN-goy9VOY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	<iframe width="560" height="315" src="https://www.youtube.com/embed/_066dEkycr4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	
	<iframe width="560" height="315" src="https://www.youtube.com/embed/jUVBHhnxeGo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	<iframe width="560" height="315" src="https://www.youtube.com/embed/TPpoJGYlW54" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Corona Virus | Info India | Pandemic 2020 </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <meta charset="UTF-8">
  <meta name="description" content="Statistics and Information about Corona Virus (Covid19) pandemic in India. State Wise Information on Corona Virus spread">
   <meta name="keywords" content="corona virus india map,confirmed cases, lockdown , latest , live update, numbers , news,pandemic">
     <meta name="author" content="Arpit Sachdeva">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <!-- Global site tag (gtag.js) - Google Analytics -->

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-161442022-1"></script>
<link href="https://fonts.googleapis.com/css?family=Righteous&display=swap" rel="stylesheet">
     <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-161442022-1');
</script>
 <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.css">
       <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <%= favicon_link_tag asset_path('cv.png') %>
 </head>

  <body>
    <div id="header">
      <div id="hl">
        <h1 style="color:#4edcc1;">Info</h1><h1 style="color: #d8442c;">Corona</h1><h1 style="color: #f5ac39;">Virus</h1><h1 style="color:#f13fc4;">.In</h1>
      </div>
      <div id="hr">
      </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav" id="subheadernav">
      <a class="nav-item nav-link" href=<%=info_path%>>Information </a>
      <a class="nav-item nav-link" href=<%=root_path%>>Statistics</a>
       <a class="nav-item nav-link" href=<%=blog_index_path%>>Blog</a>
    <!--   <a class="nav-item nav-link" href="#">Blog</a>
      <a class="nav-item nav-link" href="#">Prevention</a> -->
    </div>
  </div>
</nav>
    <%= yield %>
    <div id="footer">
      <div>
        <p>
          For further queries contact-:<br>
          arpitdeveloper03@gmail.com
        </p>
      </div>
      <div>
        <p>
          All Data has been fetched from Ministry of Health India.<br>
          <a href="https://www.mohfw.gov.in">https://www.mohfw.gov.in</a>
        </p>
      </div>
    </div>

    <script type="text/javascript" src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
  
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
  </body>
</html>

app/views/prevent/index.html.erb
<h1>Prevent#index</h1>
<p>Find me in app/views/prevent/index.html.erb</p>